"""Tiny UI helpers shared across widgets."""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QSize
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QPushButton, QWidget

_ASSETS = Path(__file__).resolve().parents[1] / "assets"


def mic_icon_idle() -> QIcon:
    return QIcon(str(_ASSETS / "mic_button.png"))


def mic_icon_recording() -> QIcon:
    return QIcon(str(_ASSETS / "mic_button_recording.png"))


def apply_mic_icon(btn: QPushButton, recording: bool = False) -> None:
    """Set the appropriate mic glyph + sizing on a mic button.

    The button face is the full app-icon look (dark rounded square + glowing
    mic), generated by scripts/build_icon.py. No QSS background; the PNG is
    the button.
    """
    btn.setText("")
    btn.setIcon(mic_icon_recording() if recording else mic_icon_idle())
    btn.setIconSize(QSize(48, 48))


def restyle(widget: QWidget) -> None:
    """Force Qt to re-evaluate QSS after a dynamic property change.

    The #1 PySide gotcha: changing a property used in a QSS selector (e.g.
    `[active="true"]`) does NOT trigger a restyle by default. Call this after
    every `setProperty(...)` that's referenced in the stylesheet.
    """
    style = widget.style()
    if style is None:
        return
    style.unpolish(widget)
    style.polish(widget)
    widget.update()


def set_class(widget: QWidget, class_name: str) -> None:
    """Add a CSS-style class to a widget.

    Qt QSS selects by class via `QClassName.className` style — we use the
    `class` dynamic property which we read in selectors as `[class~="card"]`.
    To keep the QSS readable we use `QFrame.card { ... }` with `class` set as a
    plain dynamic property here. Multiple classes can be space-separated.
    """
    existing = widget.property("class") or ""
    classes = set(existing.split())
    classes.add(class_name)
    widget.setProperty("class", " ".join(sorted(classes)))
    restyle(widget)
